### ISSUE TITLE
Not working with pouch-4.0.0???

### ISSUE THREAD

**Issue by wishabhilash** [nolanlawson/pouchdb-find#55]
Am using Pouchdb-4.0.0 and requirejs.
In require config:
```json
    paths: {
        pouchdb: './lib/assets/pouchdb/pouchdb-4.0.0.min',
        pouchdb_find: './lib/assets/pouchdb/pouchdb.find.min'
    }
```
and...
```json
    shim: {
        pouchdb_find: {
		deps: ['pouchdb'],
		exports: 'pouchdb_find'
	}
    }
```
Also included it in the define file after pouchdb:
``` json   
    'pouchdb',
    'pouchdb_find',
```

It throws error:
    db.find is not a function.

What might be wrong in this???

**Comment by nolanlawson** [comment]
I don't believe pouchdb-find works with requirejs, as is. You can build a browserify standalone build, and that should work: http://wzrd.in/standalone/pouchdb-find@latest

**Comment by nolanlawson** [comment]
Nothing changed in 4.0.0 that should break pouchdb-find, though.

**Comment by wishabhilash** [comment]
I tested pouchdb-find with v4 and it works. No problem there. But it would be awesome if it worked with requirejs. Lemme see if I can make it happen. Will ask for a pull request then.

**Comment by wishabhilash** [comment]
@nolanlawson : Thanks man. Finally I could make it work with requirejs. :)

**Comment by agozie** [comment]
I have been having same problem with using pouchdb-find in web worker. Same db.find is not a function.

**Comment by nolanlawson** [comment]
@agozie If you're seeing `db.find is not a function` then the plugin hasn't been loaded. Are you sure you called `PouchDB.plugin(pouchdbFind)`, which you must do if you are using RequireJS?

**Comment by agozie** [comment]
@nolanlawson thanks, I didn't know about `PouchDB.plugin(pouchdbFind)`. It solved my issue.
